# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bookcharts',
                'doc_host': 'https://c-a-s-t-l-e.github.io',
                'git_url': 'https://github.com/c-a-s-t-l-e/bookcharts.git',
                'lib_path': 'bookcharts'},
  'syms': {'bookcharts.core': {'bookcharts.core.foo': ('core.html#foo', 'bookcharts/core.py')}}}
